### ISSUE TITLE
addtagid causes error

### ISSUE THREAD

**Issue by jonestristand** [alphapapa/pyza#2]
In method _addTags, line 433. Causes an eventual error in python-mpd2 (mpd.py line 275 in _read_line). Not sure why, it seems that the tagging commands get interpreted as ERROR_PREFIX. Is this an issue with python-mpd2 or in pyza?

Traceback (most recent call last):
  File "./pyza", line 1000, in <module>
    sys.exit(main())
  File "./pyza", line 984, in main
    player.play()
  File "./pyza", line 495, in play
    super(MPD, self).play()
  File "./pyza", line 337, in play
    self.next()
  File "./pyza", line 329, in next
    self._next()
  File "./pyza", line 404, in _next
    self._getNextTrack()
  File "./pyza", line 397, in _getNextTrack
    self.nextSongID = self._add(self.nextTrack)
  File "./pyza", line 433, in _add
    self._addTags(songID, track)
  File "./pyza", line 455, in _addTags
    self.mpd.addtagid(songID, 'artist', track.artist)
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 600, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 238, in _execute
    return retval()
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 595, in decorator
    return function(self, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 363, in _fetch_nothing
    line = self._read_line()
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 275, in _read_line
    raise CommandError(error)
mpd.CommandError: [5@0] {} unknown command "addtagid"

**Comment by jonestristand** [comment]
Sorry, just need to have MPD version > 0.19.0 to have addtagid commands.

**Comment by alphapapa** [comment]
Hey, I just noticed this issue you reported several months ago.  Since you closed it right away, it didn't show up very high in my list, I guess.  :)  Anyway, thanks for reporting it.  I added some code to detect the MPD version and not try to add tags if it's older than 0.19, and it'll print a warning recommending an upgrade.
